# Generated by Django 3.2.6 on 2021-08-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210831_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author_name',
            new_name='name',
        ),
    ]
