# Generated by Django 3.2.6 on 2021-08-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_author_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_name',
            new_name='authorName',
        ),
    ]
