# Generated by Django 3.2.6 on 2021-08-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_author_name_article_authorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorName',
            new_name='author_name',
        ),
    ]
