# Generated by Django 3.2.6 on 2021-08-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_author_name_article_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Product',
            new_name='author_name',
        ),
    ]
