# Generated by Django 3.2.6 on 2021-08-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210831_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
    ]
