# Generated by Django 3.2.6 on 2021-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
