# Generated by Django 3.2.6 on 2021-08-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210831_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='author_name',
        ),
    ]
