# Generated by Django 3.2.6 on 2021-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_rename_name_article_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
